import Articles from "@/components/home/articles";
import HomeBanner from "@/components/home/banner";
import CeoWord from "@/components/home/ceoWord";
import InterventionCategories from "@/components/home/interventionCategories";
import Temoignages from "@/components/home/temoignages";
import Layout from "@/components/layout";
import http from "@/libs/axios";
import {
  Page,
  InterventionCategory as InterventionCategoryT,
} from "@/__typescript";
import axios from "axios";
import Head from "next/head";
import Image from "next/image";

export default function Home({ page, services, temoignages, articles }: any) {
  const {
    data: { attributes },
  } = page;

  const {
    data: { attributes: temoignagesAttributes },
  } = temoignages;

  return (
    <>
      <Head>
        <title>Health travel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <HomeBanner banner={attributes.banner} />
        <CeoWord data={attributes.ceo_word} />
        <InterventionCategories
          servicesContent={attributes.services_content}
          categories={services.data}
        />

        <Temoignages temoignages={temoignagesAttributes.temoignages} />

        <Articles articles={articles.data} />
      </Layout>
    </>
  );
}

export async function getStaticProps(context: any) {
  const promises = [
    http.get(
      "/home?populate[banner][populate]=*&populate[services_content][populate]=*&populate[ceo_word][populate]=*"
    ),
    http.get("/services?populate=*"),
    http.get("/temoignage?populate[temoignages][populate]=*"),
    http.get("/articles?populate=*"),
  ];

  const [page, services, temoignages, articles] = await Promise.all(promises);

  return {
    props: {
      page: page.data,
      services: services.data,
      temoignages: temoignages.data,
      articles: articles.data,
    },
  };
}
